import Header from '@/components/header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {ReactNode} from "react";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Car Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={'flex flex-col'}>
      <Header />
      <main className={'py-5 flex-auto'}>
        {children}
      </main>
      <Footer />
      </body>
    </html>
  )
}
